"""HTML report generation for DNSimple domain audit."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from dnsimple_cli.models import Domain
from dnsimple_cli.storage import Storage, get_db_path


class ReportError(Exception):
    """Error during report generation."""

    pass


# Colour name -> (badge classes, contents-link classes). A category picks one by name.
PALETTE: dict[str, tuple[str, str]] = {
    "purple": ("bg-purple-100 text-purple-800", "text-purple-600 hover:text-purple-800"),
    "blue": ("bg-blue-100 text-blue-800", "text-blue-600 hover:text-blue-800"),
    "green": ("bg-green-100 text-green-800", "text-green-600 hover:text-green-800"),
    "amber": ("bg-amber-100 text-amber-800", "text-amber-600 hover:text-amber-800"),
    "gray": ("bg-gray-100 text-gray-800", "text-gray-600 hover:text-gray-800"),
}


def get_categories(data: dict[str, Any]) -> list[dict[str, str]]:
    """Domain categories for the report, in display order.

    Declared by the optional top-level ``categories`` list in the recommendations file:
    ``{"key", "title", "label"?, "id"?, "color"?}`` — ``title`` heads the section,
    ``label`` is the per-group badge, ``color`` is a PALETTE name.
    """
    declared = data.get("categories")
    if declared:
        cats = [dict(c) for c in declared]
    else:
        # fallback: no declared categories — one per distinct group category, in order seen
        keys = list(dict.fromkeys(g["category"] for g in data.get("groups", [])))
        cats = [{"key": k, "title": k.replace("_", " ").title()} for k in keys]
    colours = list(PALETTE)
    for i, c in enumerate(cats):
        c.setdefault("label", c["title"])
        c.setdefault("id", c["key"].replace("_", "-"))
        if c.get("color") not in PALETTE:
            c["color"] = colours[i % len(colours)]
    return cats


def get_recommendations_path() -> Path:
    """Get path to recommendations JSON file."""
    return get_db_path().parent / "report-recommendations.json"


def load_recommendations() -> dict[str, Any]:
    """Load and validate the AI-generated recommendations JSON.

    Returns:
        Parsed recommendations data

    Raises:
        ReportError: If file missing or invalid
    """
    path = get_recommendations_path()

    if not path.exists():
        raise ReportError(
            f"Recommendations file not found: {path}\n\n"
            "This file must be generated by Claude before running the report.\n"
            "Ask Claude to analyze your domain data and generate recommendations."
        )

    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        raise ReportError(f"Invalid JSON in recommendations file: {e}") from e

    # Validate required fields
    if "groups" not in data:
        raise ReportError("Recommendations file missing 'groups' field")

    if not isinstance(data["groups"], list):
        raise ReportError("'groups' must be a list")

    declared = data.get("categories")
    if declared is not None:
        if not isinstance(declared, list) or not all(
            isinstance(c, dict) and "key" in c and "title" in c for c in declared
        ):
            raise ReportError("'categories' must be a list of {key, title, ...} objects")
    valid_categories = [c["key"] for c in get_categories(data)]

    for i, group in enumerate(data["groups"]):
        required = ["name", "category", "primary_domain", "domains", "recommendations"]
        for field in required:
            if field not in group:
                raise ReportError(f"Group {i} missing required field: {field}")

        if group["category"] not in valid_categories:
            raise ReportError(
                f"Group '{group['name']}' has invalid category: {group['category']}. "
                f"Must be one of: {valid_categories}"
            )

        for j, rec in enumerate(group["recommendations"]):
            rec_required = ["severity", "title", "description"]
            for field in rec_required:
                if field not in rec:
                    raise ReportError(
                        f"Recommendation {j} in group '{group['name']}' "
                        f"missing required field: {field}"
                    )

            valid_severities = ["info", "warning", "error"]
            if rec["severity"] not in valid_severities:
                raise ReportError(
                    f"Recommendation '{rec['title']}' has invalid severity. "
                    f"Must be one of: {valid_severities}"
                )

    return data


def generate_report(output_dir: Path | None = None) -> Path:
    """Generate the HTML audit report.

    Args:
        output_dir: Directory for output file. Defaults to 'reports/' in project.

    Returns:
        Path to generated HTML file

    Raises:
        ReportError: If recommendations missing or invalid
    """
    # Load recommendations
    recommendations = load_recommendations()

    # Load domain data
    with Storage() as storage:
        all_domains = storage.load_domains(include_subdomains=True)
        metadata = storage.get_metadata()

    # Build domain lookup
    domains_by_name = {d.name: d for d in all_domains}

    # Determine output path
    if output_dir is None:
        output_dir = get_db_path().parent.parent / "reports"
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    output_path = output_dir / f"audit-{timestamp}.html"

    # Render HTML
    html = render_html(recommendations, domains_by_name, metadata)
    output_path.write_text(html)

    return output_path


def render_html(
    recommendations: dict[str, Any],
    domains_by_name: dict[str, Domain],
    metadata: Any,
) -> str:
    """Render the HTML report."""

    # Category styling, from the recommendations file (see get_categories)
    cat_list = get_categories(recommendations)
    category_styles = {c["key"]: (c["label"], PALETTE[c["color"]][0]) for c in cat_list}

    severity_styles = {
        "info": ("bg-gray-100 text-gray-800", "text-gray-600"),
        "warning": ("bg-amber-100 text-amber-800", "text-amber-600"),
        "error": ("bg-red-100 text-red-800", "text-red-600"),
    }

    def render_domain_card(domain: Domain, is_primary: bool) -> str:
        """Render a single domain card."""
        primary_badge = (
            '<span class="ml-2 px-2 py-0.5 text-xs bg-indigo-100 text-indigo-800 rounded">Primary</span>'
            if is_primary
            else ""
        )

        # Services
        services_html = ""
        if domain.services:
            services_list = ", ".join(s.provider for s in domain.services)
            services_html = f"""
            <div class="mt-2">
                <span class="text-xs font-medium text-gray-500">Services:</span>
                <span class="text-sm text-gray-700">{services_list}</span>
            </div>"""

        # Apps
        apps_html = ""
        if domain.apps:
            apps_list = ", ".join(f"{a.subdomain}→{a.provider}" for a in domain.apps)
            apps_html = f"""
            <div class="mt-1">
                <span class="text-xs font-medium text-gray-500">Apps:</span>
                <span class="text-sm text-gray-700">{apps_list}</span>
            </div>"""

        # Email MX
        mx_html = ""
        if domain.email_mx:
            mx_html = f"""
            <div class="mt-1">
                <span class="text-xs font-medium text-gray-500">Email MX:</span>
                <span class="text-sm text-gray-700">{domain.email_mx.provider}</span>
            </div>"""

        # Email SMTP
        smtp_html = ""
        if domain.email_smtp:
            smtp_list = ", ".join(s.provider for s in domain.email_smtp)
            smtp_html = f"""
            <div class="mt-1">
                <span class="text-xs font-medium text-gray-500">Email SMTP:</span>
                <span class="text-sm text-gray-700">{smtp_list}</span>
            </div>"""

        border_class = "border-indigo-300 border-2" if is_primary else "border-gray-200"

        # Health check link (only for primary domains, not subdomains)
        health_link = ""
        if not domain.parent_domain:
            health_link = f"""
            <a href="https://mxtoolbox.com/emailhealth/{domain.name}/"
               target="_blank" rel="noopener"
               class="text-xs text-blue-500 hover:text-blue-700 hover:underline">Health Check &nearr;</a>"""

        return f"""
        <div class="bg-white rounded-lg shadow-sm p-4 {border_class}">
            <div class="flex items-center justify-between">
                <div class="flex items-center">
                    <h4 class="font-medium text-gray-900">{domain.name}</h4>
                    {primary_badge}
                </div>
                {health_link}
            </div>
            <div class="text-xs text-gray-400 mt-1">{len(domain.records)} records</div>
            {services_html}
            {apps_html}
            {mx_html}
            {smtp_html}
        </div>"""

    def render_recommendations(recs: list[dict]) -> str:
        """Render recommendations list."""
        if not recs:
            return '<p class="text-gray-500 italic">No recommendations for this group.</p>'

        items = []
        for rec in recs:
            badge_style, text_style = severity_styles[rec["severity"]]
            affected = ""
            if rec.get("affected_domains"):
                affected = f"""
                <div class="mt-1 text-xs text-gray-500">
                    Affects: {", ".join(rec["affected_domains"])}
                </div>"""

            items.append(f"""
            <div class="flex items-start gap-3 py-2">
                <span class="px-2 py-0.5 text-xs font-medium rounded {badge_style}">
                    {rec["severity"].upper()}
                </span>
                <div class="flex-1">
                    <div class="font-medium text-gray-900">{rec["title"]}</div>
                    <div class="{text_style} text-sm">{rec["description"]}</div>
                    {affected}
                </div>
            </div>""")

        return "\n".join(items)

    def render_group(group: dict) -> str:
        """Render a domain group section."""
        category_label, category_class = category_styles[group["category"]]

        # Render domain cards
        domain_cards = []
        for domain_name in group["domains"]:
            domain = domains_by_name.get(domain_name)
            if domain:
                is_primary = domain_name == group["primary_domain"]
                domain_cards.append(render_domain_card(domain, is_primary))

                # Also render subdomains
                for sub_name, sub_domain in domains_by_name.items():
                    if sub_domain.parent_domain == domain_name:
                        domain_cards.append(render_domain_card(sub_domain, False))

        return f"""
        <section class="mb-8">
            <div class="flex items-center gap-3 mb-4">
                <h2 class="text-xl font-bold text-gray-900">{group["name"]}</h2>
                <span class="px-2 py-1 text-xs font-medium rounded {category_class}">
                    {category_label}
                </span>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
                {"".join(domain_cards)}
            </div>

            <div class="bg-gray-50 rounded-lg p-4">
                <h3 class="font-medium text-gray-900 mb-2">Recommendations</h3>
                {render_recommendations(group["recommendations"])}
            </div>
        </section>"""

    # Group by category
    categories = {c["key"]: {"title": c["title"], "id": c["id"], "groups": []} for c in cat_list}

    for group in recommendations["groups"]:
        cat = group["category"]
        if cat in categories:
            categories[cat]["groups"].append(group)

    def render_category_section(cat_key: str, cat_data: dict) -> str:
        """Render a category section with H1 and all its groups."""
        if not cat_data["groups"]:
            return ""

        groups_html = "\n".join(render_group(g) for g in cat_data["groups"])
        return f"""
        <section id="{cat_data['id']}" class="mb-12">
            <h1 class="text-2xl font-bold text-gray-900 mb-6 pb-2 border-b-2 border-gray-300">
                {cat_data['title']}
            </h1>
            {groups_html}
        </section>"""

    # Build all category sections
    sections_html = "\n".join(
        render_category_section(k, v)
        for k, v in categories.items()
        if v["groups"]
    )

    # Contents links, one per category
    contents_links = "\n                ".join(
        f'<a href="#{c["id"]}" class="{PALETTE[c["color"]][1]} font-medium">{c["title"]}</a>'
        for c in cat_list
    )

    # Summary stats
    primary_count = len([d for d in domains_by_name.values() if d.parent_domain is None])
    subdomain_count = len([d for d in domains_by_name.values() if d.parent_domain is not None])

    total_recommendations = sum(
        len(g["recommendations"]) for g in recommendations["groups"]
    )
    error_count = sum(
        1
        for g in recommendations["groups"]
        for r in g["recommendations"]
        if r["severity"] == "error"
    )
    warning_count = sum(
        1
        for g in recommendations["groups"]
        for r in g["recommendations"]
        if r["severity"] == "warning"
    )

    sync_time = metadata.synced_at.strftime("%Y-%m-%d %H:%M") if metadata else "Unknown"
    rec_time = recommendations.get("generated_at", "Unknown")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DNSimple Domain Audit Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 min-h-screen">
    <div class="max-w-6xl mx-auto py-8 px-4">
        <header class="mb-8">
            <h1 class="text-3xl font-bold text-gray-900">DNSimple Domain Audit Report</h1>
            <p class="text-gray-500 mt-1">Generated {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
        </header>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
            <div class="bg-white rounded-lg shadow-sm p-4">
                <div class="text-2xl font-bold text-gray-900">{primary_count}</div>
                <div class="text-sm text-gray-500">Primary Domains</div>
            </div>
            <div class="bg-white rounded-lg shadow-sm p-4">
                <div class="text-2xl font-bold text-gray-900">{subdomain_count}</div>
                <div class="text-sm text-gray-500">Subdomains</div>
            </div>
            <div class="bg-white rounded-lg shadow-sm p-4">
                <div class="text-2xl font-bold text-amber-600">{warning_count}</div>
                <div class="text-sm text-gray-500">Warnings</div>
            </div>
            <div class="bg-white rounded-lg shadow-sm p-4">
                <div class="text-2xl font-bold text-red-600">{error_count}</div>
                <div class="text-sm text-gray-500">Errors</div>
            </div>
        </div>

        <nav class="bg-white rounded-lg shadow-sm p-4 mb-8">
            <h2 class="text-sm font-medium text-gray-500 mb-2">Contents</h2>
            <div class="flex gap-4">
                {contents_links}
            </div>
        </nav>

        {sections_html}

        <footer class="mt-8 pt-4 border-t border-gray-200 text-sm text-gray-500">
            <div>Data synced: {sync_time}</div>
            <div>Recommendations generated: {rec_time}</div>
            <div>Report generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</div>
        </footer>
    </div>
</body>
</html>"""
